# fly.toml file generated for proud-tree-6354 on 2023-04-04T16:53:06+09:00

app = "proud-tree-6354"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "nrt"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
